#!/bin/sh

set -e

uci -q batch <<EOI
set system.@system[0].conloglevel='5'
set system.@system[0].cronloglevel='8'
set system.@system[0].hostname='openwrt'
set system.@system[0].log_proto='udp'
set system.@system[0].log_size='64'
set system.@system[0].timezone='CST-8'
set system.@system[0].ttylogin='0'
set system.@system[0].urandom_seed='0'
set system.@system[0]=system
commit system
EOI

while uci -q delete dropbear.@dropbear[0]; do :; done
uci commit dropbear

uci -q batch <<EOI
add dropbear dropbear
set dropbear.@dropbear[-1].PasswordAuth='on'
set dropbear.@dropbear[-1].Port='22'
set dropbear.@dropbear[-1].Interface='lan'
commit dropbear
EOI

# The following is only work for x86 openwrt
if [ -f /boot/grub/grub.cfg ]; then
    sed -i -e 's/set timeout="5"/set timeout="1"/g' /boot/grub/grub.cfg
fi

if command -v tmux; then
    cat <<EOF | tee /etc/tmux.conf
    set -g buffer-limit 10000
    set -g history-limit 5000
    set -g renumber-windows on
EOF
    if command -v fish; then
        echo "set -g default-shell $(command -v fish)" | tee -a /etc/tmux.conf
    elif command -v bash; then
        echo "set -g default-shell $(command -v bash)" | tee -a /etc/tmux.conf
    fi
fi

exit 0
